zowe/zowe-cli-db2-plugin

CONTRIBUTING.md

Signed-off-by: bauja03 <bauja03@ca.com>

fixed links in the table

---

Jenkinsfile
README.md

Signed-off-by: bauja03 <james.bauman@broadcom.com>
- Fixed broken links in the readme file.

fixed all broken links

---

zowe-cli-db2-plugin.ppf

Signed-off-by: Yan Li <raymondyanli@gmail.com>
@MarkAckert Please review the AppScan configure file for zowe-cli-db2-plugin.
cc @jackjia-ibm

adding AppScan config file

---

.codecov.yml
Jenkinsfile
README.md

Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

Add Codecov settings

---

__tests__/__src__/Db2TestConstants.ts
__tests__/__system__/cli/execute/cli.db2.execute.sql.system.test.ts
__tests__/api/DB2Error.test.ts
__tests__/api/__snapshots__/DB2Error.test.ts.snap
src/api/CallSP.ts
src/api/DB2Error.ts
src/api/ExecuteSQL.ts
src/api/ExportTable.ts

Provide more information in error messages

Improve Error Messages

---

CONTRIBUTING.md
README.md

The PR includes:
- rename/rebranded the name of the plug-in
- reorganized content to be consistent with respect to structure

Merge updated README and CONTRIBUTING articles into Master

---

Jenkinsfile
README.md
package.json

Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>
Part of https://github.com/zowe/zowe-install-packaging/issues/875

switch to zowe artifactory

---

.npmrc

Fix .npmrc in master branch to point to the right Zowe registry

---

Jenkinsfile

Update credential ID for new Zowe artifactory

---

Jenkinsfile
package.json

Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Use proper version of CLI and update Jenkins to handle V1-LTS

---

CHANGELOG.md

The most minor of changelog updates, for formatting.

Minor changelog update

---

CHANGELOG.md
package.json

Resolves #72.
Updated TypeDoc dependency which was breaking the vulnerabilities check in Jenkins.
Also updated the Ts-Jest dependency that created a low vulnerability warning.

Updated dependencies

---

CHANGELOG.md
package.json

Remove @zowe/cli peer dependency to better support NPM v7

Remove peer deps next

---

.npmrc

Update registry in npmrc to use https

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

⚠️ Do not merge until zowe-cli-version-controller is fixed to prune dev deps from shrinkwrap

[next] Republish to prune dev dependencies from shrinkwrap

---

CHANGELOG.md
npm-shrinkwrap.json

[next] Update follow-redirects dependency

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Update ibm_db dependency to better support M1 Mac - note that the binary DOES NOT WORK, only installs.

Update ibmdb next

---

.github/workflows/audit.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
.github/workflows/zowe-cli-plugin.yml
Jenkinsfile
package.json

Update protected branch list and package author

---

.github/workflows/audit.yml
.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json
package.json

Backports #109 to zowe-v1-lts branch

[zowe-v1-lts] Update ibm_db to support Node.js 18

---

.github/workflows/zowe-cli-plugin.yml

Fixes a build failure on Node 14 which was using an outdated and unsupported version of NPM in the pipelines.

Fix build failure

---

.github/workflows/zowe-cli-plugin.yml
README.md

Replicate the recent documentation changes and workflow fixes in V1 LTS
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>

Update README and workflows in V1

---

CHANGELOG.md
npm-shrinkwrap.json

Same as #114 but for master branch

Update the version of minimatch being distributed

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json
package.json

Updates ibm_db for technical currency

Update ibm_db in v1

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json
package.json

Updates ibm_db to 3.2.2 to resolve technical debt

Update ibm_db in v2

---

CHANGELOG.md
npm-shrinkwrap.json

Resolves technical currency by updating the follow-redirects transitive dependency

Update follow-redirects (v1)

---

CHANGELOG.md
npm-shrinkwrap.json

Resolves technical currency by updating the follow-redirects transitive dependency

Update follow-redirects (v2)

---

.github/workflows/audit.yml
.github/workflows/auto-comment.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
.github/workflows/stale.yml
.github/workflows/zowe-cli-plugin.yml

Update the workflow to use Node 20 workflows

Update Workflows to Node 20

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json

Update axios dependency for technical debt
Update workflow to use macos-13 (x86)

Update deps (V1)

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json

Updates `axios` to resolve technical debt.
Updates workflow to use macos-13 (x86).

Update deps (V2)

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json

Updates `axios` transitive dependency to resolve technical debt.
Updates workflow to use macos-13 (x86).

Update deps (V3)

---

.github/workflows/codeql.yml

Updates CodeQL workflow version to v3

Update CodeQL workflow version

---

CHANGELOG.md
npm-shrinkwrap.json

Updates axios transitive dependency to resolve technical debt

Update Axios Transitive Dependency [v2]

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json

Updated axios transitive dependency to resolve technical currency

Update Axios Transitive Dependency [v1]

---

CHANGELOG.md
npm-shrinkwrap.json

Update Axios transitive dependency for technical currency

Update Axios Transitive Dependency [v3]

---

CONTRIBUTING.md

Update the Imperative Wiki link

Update Imperative Wiki Link

---

CHANGELOG.md
CONTRIBUTING.md
npm-shrinkwrap.json
package.json
release.config.js

This PR updates the next branch with master.
Also, updates the release config to allow for a final prerelease to be published from the master branch.

Prepare `next` to be merged into`master`

---

CHANGELOG.md
release.config.js

chore: update release config to publish a major version

---

.github/workflows/zowe-cli-plugin.yml
CHANGELOG.md
npm-shrinkwrap.json
package.json

Also updates ibm_db dependency to support Node.js 22 on Windows (w/o enhancement for M1 Macs)

[v2] Update workflows and deps for technical currency

---

CHANGELOG.md
npm-shrinkwrap.json

Updated axios transitive dependency to resolve technical debt.

---

CHANGELOG.md
npm-shrinkwrap.json

v2: Update tar-fs dependency

---

CHANGELOG.md
npm-shrinkwrap.json

Update tar-fs dependency

---

CHANGELOG.md
npm-shrinkwrap.json

Update workflows and deps for technical currency

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Fix offline installation requirement of an undocumented env variable (v2)

---

CHANGELOG.md
npm-shrinkwrap.json

Update dependencies to fix audit

Update dependencies (V2)
